sudo: required

services:
  - docker

env:
  matrix:
    - EXAMPLE="01-simple"
    - EXAMPLE="02-data-container"
    - EXAMPLE="03-drush"

before_script:
  - docker version
  - docker-compose version
  - cd examples/${EXAMPLE}

script:
  - docker-compose up -d
  - sleep 10
  - [[ -e "./tesh.sh" ]] && ./tesh.sh || echo "Missing test"

after_script:
  - docker ps -a
